[package]
name = "atlas-server"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
atlas-core = { version = "0.1.0", path = "../atlas-core" }
atlas-rig = { version = "0.1.0", path = "../atlas-rig" }
axum = { version = "0.8.9", features = ["ws"] }
base64 = "0.23.1"
bytes = "1.12.1"
dirs = "7.0.0"
futures-util = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
subtle = "2.6.1"
tokio = { version = "1.53.2", features = ["full"] }
toml = "1.1.7"
toml_edit = "0.25.16"
tower-http = { version = "0.7.1", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
tokio-tungstenite = "0.30.0"
